### ISSUE TITLE
Homepage menu css problems

### ISSUE THREAD

**Issue by allbombs** [stringbeans/homelesspartners#88]
<img width="1280" alt="screen shot 2015-11-10 at 4 47 20 pm" src="https://cloud.githubusercontent.com/assets/2031239/11058038/e5f7ec7e-87ca-11e5-940d-e419d8860ed0.png">

When scrolling up and down the page, there are strange lines displayed within the nav bar menu

**Comment by rbao** [comment]
This is strange bug, as far as i know it only happens on Chrome and on Retina Display. Initial investigation makes me think its due to the hovering effect of 'Cities'. The line changes place while hovering on cities.

**Comment by mikemartin** [comment]
Hey guys,
I'm still subscribed on this repo so I was notified about the issue. :+1: 
I took a like myself and this appears to have something to do with the homeless partners logo (navbar-brand). We're using a @2x version of the logo for retina screens, so that explains why it appears on retina display.

I'll continue looking, but I hope that helps. :)

**Comment by mikemartin** [comment]
Okay, there appears to be a conflict with the text replacement method I used to hide Homeless Partners text. I'd suggest removing this line and hiding/removing the text another way.
.navbar-brand { text-indent: -9999999px; }

**Comment by mikemartin** [comment]
@rbao Feel free to reach out if you have any other CSS questions. You can reach me at mikemartin604@gmail.com or twitter @mikemartin604.

**Comment by rbao** [comment]
@mikemartin you are amazing! Removed the text-indent and positioned the text offscreen works well. Thanks for the help!

**Comment by allbombs** [comment]
Merci @mikemartin!!!!! 

🍾

**Comment by mikemartin** [comment]
@allbombs No problem at all! I'll stay subscribed on the project and watch over you guys. If you need me, just summon me. :+1:
